import path from "path";
import fs from "fs-extra";

const ROOT = process.cwd();

export const paths = {
  root: ROOT,

  // Folders
  circuits: path.join(ROOT, "circuits"),
  inputs: path.join(ROOT, "inputs"),
  outputs: path.join(ROOT, "outputs"),

  // Common files
  circuitFile: path.join(ROOT, "circuits", "schema.circom"),
  inputJson: path.join(ROOT, "inputs", "inputs.json"),

  // Generated by circom
  wasm: path.join(ROOT, "outputs", "schema_js", "schema.wasm"),
  witnessJs: path.join(ROOT, "outputs", "schema_js", "generate_witness.js"),
  r1cs: path.join(ROOT, "outputs", "schema.r1cs"),

  // Trusted setup files
  pot0: path.join(ROOT, "pot12_0000.ptau"),
  pot1: path.join(ROOT, "pot12_0001.ptau"),
  potFinal: path.join(ROOT, "pot12_final.ptau"),

  // Groth16 files
  zkey: path.join(ROOT, "circuit_0000.zkey"),
  vkey: path.join(ROOT, "verification_key.json"),

  // Proof files
  witnessWtns: path.join(ROOT, "outputs", "witness.wtns"),
  proofJson: path.join(ROOT, "proof.json"),
  publicJson: path.join(ROOT, "public.json"),
};

// Optional: ensure folders exist
export function ensureBaseFolders() {
  fs.ensureDirSync(paths.circuits);
  fs.ensureDirSync(paths.inputs);
  fs.ensureDirSync(paths.outputs);
}
